<?php
return[
    'basePath'=>'/MVC-vanilla/public',
    'rootDir'=>dirname(dirname(__FILE__)),//MVCPHP
    'layout'=>'layouts/main',
    'db'=>[
        'host'=>'127.0.0.1',
        'post'=>'3306',
        'username'=>'root',
        'password'=>''
    ]
];